//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCshop.Resources.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpamDisplay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpamDisplay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NYCshop.Resources.ResourceFiles.SpamDisplay", typeof(SpamDisplay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo đúng.
        /// </summary>
        public static string ProperReport {
            get {
                return ResourceManager.GetString("ProperReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày báo cáo vi phạm.
        /// </summary>
        public static string ReportDate {
            get {
                return ResourceManager.GetString("ReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người báo cáo.
        /// </summary>
        public static string Reporter {
            get {
                return ResourceManager.GetString("Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã giải quyết hay chưa.
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giải quyết.
        /// </summary>
        public static string ResolveDate {
            get {
                return ResourceManager.GetString("ResolveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người giải quyết.
        /// </summary>
        public static string Resolver {
            get {
                return ResourceManager.GetString("Resolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung vi phạm.
        /// </summary>
        public static string SpamContent {
            get {
                return ResourceManager.GetString("SpamContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vi phạm.
        /// </summary>
        public static string SpamID {
            get {
                return ResourceManager.GetString("SpamID", resourceCulture);
            }
        }
    }
}
