//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCshop.Resources.DataAccessMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WishListDAOMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WishListDAOMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NYCshop.Resources.DataAccessMessage.WishListDAOMsg", typeof(WishListDAOMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm vào Danh sách sản phẩm muốn mua thất bại.
        /// </summary>
        public static string AddProdToWishListFailed {
            get {
                return ResourceManager.GetString("AddProdToWishListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm vào Danh sách sản phẩm muốn mua vào CSDL thất bại.
        /// </summary>
        public static string AddProdToWishListInDbFailed {
            get {
                return ResourceManager.GetString("AddProdToWishListInDbFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm vào Danh sách sản phẩm muốn mua vào CSDL thành công.
        /// </summary>
        public static string AddProdToWishListInDbSuccessful {
            get {
                return ResourceManager.GetString("AddProdToWishListInDbSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm vào Danh sách sản phẩm muốn mua thành công.
        /// </summary>
        public static string AddProdToWishListSuccessful {
            get {
                return ResourceManager.GetString("AddProdToWishListSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gộp Danh sách sản phẩm muốn mua thất bại.
        /// </summary>
        public static string CombineWishListFailed {
            get {
                return ResourceManager.GetString("CombineWishListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gộp Danh sách sản phẩm muốn mua thành công.
        /// </summary>
        public static string CombineWishListSuccessfull {
            get {
                return ResourceManager.GetString("CombineWishListSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy Danh sách sản phẩm muốn mua thất bại.
        /// </summary>
        public static string GetWishListFailed {
            get {
                return ResourceManager.GetString("GetWishListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy Danh sách sản phẩm muốn mua thành công.
        /// </summary>
        public static string GetWishListSuccessfull {
            get {
                return ResourceManager.GetString("GetWishListSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Danh sách sản phẩm muốn mua thất bại.
        /// </summary>
        public static string UpdateProdInWishListFailed {
            get {
                return ResourceManager.GetString("UpdateProdInWishListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Danh sách sản phẩm muốn mua thành công.
        /// </summary>
        public static string UpdateProdInWishListSuccessful {
            get {
                return ResourceManager.GetString("UpdateProdInWishListSuccessful", resourceCulture);
            }
        }
    }
}
